### ISSUE TITLE
Empty lines

### ISSUE THREAD

**Issue by somepaulo** [guoci/autokey-py3#23]
Hi @guoci ,

AutoKey py3 installed from AUR on Arch_x64/Gnome_3.18 seems to recognize any set abbreviations correctly, but only outputs empty lines. The example address inserts 4 blank lines. The log is full of errors (apparently generated at each attempt to replace an abbreviation) like this one:

<pre>
2016-04-05 02:13:00,909 ERROR - interface - Error in X event loop thread
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/autokey/interface.py", line 116, in __eventLoop
    method(*args)
  File "/usr/lib/python3.5/site-packages/autokey/interface.py", line 585, in __sendString
    self.__checkWorkaroundNeeded()
  File "/usr/lib/python3.5/site-packages/autokey/interface.py", line 870, in __checkWorkaroundNeeded
    w = self.app.configManager.workAroundApps
AttributeError: 'ConfigManager' object has no attribute 'workAroundApps'
</pre>

And when I pres any hotkey I set for the provided 'Get phrase from selection' script, I get this errorin the log:

<pre>
2016-04-05 02:59:47,399 INFO - service - Matched hotkey phrase/script with prompt=False
2016-04-05 02:59:47,653 INFO - config-manager - Configuration changed - rebuilding in-memory structures
</pre>

Something makes me suspect these two have the same cause. Like a missing dependency...
Please help.

Thank you.

**Comment by somepaulo** [comment]
Saving options, quitting AutoKey, then killing it in system monitor, and then restarting seems to have solved both issues.
