### ISSUE TITLE
Cannot paste via keyboard, cannot not english abbreviation.

### ISSUE THREAD

**Issue by dmgl** [guoci/autokey-py3#29]
Version and env:

```
$ pip freeze | grep -E "autokey|xlib"
autokey-py3==0.93.4
python3-xlib==0.15

$ cat /etc/*release* | grep "VERSION="
VERSION="16.04 LTS (Xenial Xerus)"

$ uname -r       
4.4.0-28-generic

GTK
ii  libgtk-3-0:amd64       3.18.9-1ubuntu3.1                    amd64
ii  libgtk2.0-0:amd64      2.24.30-1ubuntu1                     amd64
```

Some warnings:

```
/home/dm/.local/lib/python3.5/site-packages/autokey/gtkapp.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GObject, GLib

/home/dm/.local/lib/python3.5/site-packages/autokey/gtkui/notifier.py:19: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, Notify

/home/dm/.local/lib/python3.5/site-packages/autokey/gtkui/notifier.py:30: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3

/home/dm/.local/lib/python3.5/site-packages/autokey/gtkui/configwindow.py:20: PyGIWarning: GtkSource was imported without specifying a version first. Use gi.require_version('GtkSource', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Pango, GtkSource, Gdk, Gio
```

And some errors:

I edit `/home/dm/.local/lib/python3.5/site-packages/autokey/interface.py`

```
Traceback (most recent call last):
  File "/home/dm/.local/lib/python3.5/site-packages/autokey/interface.py", line 116, in __eventLoop
    method(*args)
  File "/home/dm/.local/lib/python3.5/site-packages/autokey/interface.py", line 502, in __sendStringClipboard
    self.__fillClipboard(string)
  File "/home/dm/.local/lib/python3.5/site-packages/autokey/interface.py", line 542, in __fillClipboard
    self.clipBoard.set_text(string)
```

because have error when trying to use abbreviatations

```
Traceback (most recent call last):
  File "/home/dm/.local/lib/python3.5/site-packages/autokey/interface.py", line 116, in __eventLoop
    method(*args)
  File "/home/dm/.local/lib/python3.5/site-packages/autokey/interface.py", line 502, in __sendStringClipboard
    self.__fillClipboard(string)
  File "/home/dm/.local/lib/python3.5/site-packages/autokey/interface.py", line 542, in __fillClipboard
    self.clipBoard.set_text(string)
TypeError: Gtk.Clipboard.set_text() takes exactly 3 arguments (2 given)
```

in methonds `def __fillSelection(self, string):` and `def __fillClipboard(self, string):`
use `self.selection.set_text(string, -1)` and `self.clipBoard.set_text(string, -1)`

I use russian and english keyboard layout and the main problems for me that i cannot:

- use `Paste using` - `Keyboard` - nothing happens in this variant. Program paste only dots and commas and text in english + digits, not text in russian. For example i have abbreviation `123` for `1,2,3:hello!йцукенг98` and it paste only `1,2,3:hello!98` but if i use option `Paste using` - `Clipboard (Shift+Insert)` i get - `1,2,3:hello!йцукенг98` Yippee! 

Perhaps in this variant i cannot use `<cursor>` because it paste with option `Paste using` - `Clipboard (Shift+Insert)` - `<left><left><left><left><left><left><left><left>` for positioning cursor, but cursor always at the end of string.

- cannot add abbreviation in russian - if i need `йцу` for `йцукенг` i need choose `Paste using` - `Clipboard (Shift+Insert)` and make abbreviation `qwe` - the same buttons on physical keyboards but with english layout, so i need script that add in `~/.config/autokey/data/My Phrases/.йцукенг.json` in section`"abbreviations": ["\u0439\u0446\u0443"]` my `qwe`.

```
>>> print(u"\u0439\u0446\u0443")
йцу
```

Can help to change `abbreviation from selection` script to add 2 abbreviation to phrase - `\u0439\u0446\u0443` and analog physical key in english `qwe`?

----

Log for `Paste using` - `Keyboard` phrase - `1,2,3:hello!<cursor>йцукенг98` and it paste only `1,2,3:hello!98` with cursor in bad position (where `_`) `1,2,3_:hello!98` 

```
2016-07-14 19:13:39,880 INFO - root - Initialising application
2016-07-14 19:13:39,885 INFO - root - Initialise global hotkeys
2016-07-14 19:13:39,886 INFO - config-manager - Loading config from existing file: /home/dm/.config/autokey/autokey.json
2016-07-14 19:13:39,886 DEBUG - config-manager - Loading folder at '/home/dm/.config/autokey/data/My Phrases'
2016-07-14 19:13:39,888 DEBUG - config-manager - Loading folder at '/home/dm/.config/autokey/data/Sample Scripts'
2016-07-14 19:13:39,889 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2016-07-14 19:13:39,889 DEBUG - inotify - Adding watch for /home/dm/.config/autokey/data/My Phrases
2016-07-14 19:13:39,890 DEBUG - inotify - Adding watch for /home/dm/.config/autokey/data/Sample Scripts
2016-07-14 19:13:39,890 INFO - config-manager - Successfully loaded configuration
2016-07-14 19:13:39,890 DEBUG - inotify - Adding watch for /home/dm/.config/autokey/data
2016-07-14 19:13:39,890 DEBUG - inotify - Adding watch for /home/dm/.config/autokey
2016-07-14 19:13:39,890 DEBUG - config-manager - Global settings: {'showToolbar': True, 'notificationIcon': 'autokey-status', 'recordTimingThreshold': 0.1, 'interfaceType': 'XRecord', 'promptToSave': True, 'serviceRunning': True, 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'hPanePosition': 489, 'menuTakesFocus': False, 'showTrayIcon': True, 'scriptGlobals': {}, 'sortByUsageCount': True, 'windowDefaultSize': [1920, 1034], 'triggerItemByInitial': False, 'undoUsingBackspace': True, 'columnWidths': [150, 50, 100], 'enableQT4Workaround': False, 'isFirstRun': True}
2016-07-14 19:13:39,890 INFO - service - Starting service
2016-07-14 19:13:39,909 DEBUG - interface - Modifier masks: {'<numlock>': 16, '<super>': 64, '<shift>': 1, '<hyper>': 64, '<alt>': 8, '<meta>': 8, '<ctrl>': 4, '<alt_gr>': 128, '<capslock>': 2}
2016-07-14 19:13:39,940 DEBUG - interface - Alt-Grid: XK_Alt_R, 65514
2016-07-14 19:13:39,940 DEBUG - interface - [(92, 0), (92, 2)]
2016-07-14 19:13:39,940 DEBUG - interface - X Server Keymap
2016-07-14 19:13:39,940 DEBUG - interface - [\] : [(51, 0), (51, 2)]
2016-07-14 19:13:39,940 DEBUG - interface - [|] : [(51, 1), (94, 3), (94, 4)]
2016-07-14 19:13:39,940 DEBUG - interface - [`] : [(49, 0)]
2016-07-14 19:13:39,940 DEBUG - interface - [1] : [(10, 0), (10, 2)]
2016-07-14 19:13:39,940 DEBUG - interface - [2] : [(11, 0), (11, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [3] : [(12, 0), (12, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [4] : [(13, 0), (13, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [5] : [(14, 0), (14, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [6] : [(15, 0), (15, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [7] : [(16, 0), (16, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [8] : [(17, 0), (17, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [9] : [(18, 0), (18, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [0] : [(19, 0), (19, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [-] : [(20, 0), (20, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [=] : [(21, 0), (21, 2)]
2016-07-14 19:13:39,941 DEBUG - interface - [~] : [(49, 1)]
2016-07-14 19:13:39,941 DEBUG - interface - [!] : [(10, 1), (10, 3)]
2016-07-14 19:13:39,941 DEBUG - interface - [@] : [(11, 1)]
2016-07-14 19:13:39,941 DEBUG - interface - [#] : [(12, 1)]
2016-07-14 19:13:39,941 DEBUG - interface - [$] : [(13, 1)]
2016-07-14 19:13:39,941 DEBUG - interface - [%] : [(14, 1), (14, 3)]
2016-07-14 19:13:39,941 DEBUG - interface - [^] : [(15, 1)]
2016-07-14 19:13:39,942 DEBUG - interface - [&] : [(16, 1)]
2016-07-14 19:13:39,942 DEBUG - interface - [*] : [(17, 1), (17, 3)]
2016-07-14 19:13:39,942 DEBUG - interface - [(] : [(187, 0), (18, 1), (187, 2), (18, 3)]
2016-07-14 19:13:39,942 DEBUG - interface - [)] : [(188, 0), (19, 1), (188, 2), (19, 3)]
2016-07-14 19:13:39,942 DEBUG - interface - [q] : [(24, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [w] : [(25, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [e] : [(26, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [r] : [(27, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [t] : [(28, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [y] : [(29, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [u] : [(30, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [i] : [(31, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [o] : [(32, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [p] : [(33, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [[] : [(34, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - []] : [(35, 0)]
2016-07-14 19:13:39,942 DEBUG - interface - [a] : [(38, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [s] : [(39, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [d] : [(40, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [f] : [(41, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [g] : [(42, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [h] : [(43, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [j] : [(44, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [k] : [(45, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [l] : [(46, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [;] : [(47, 0), (13, 3)]
2016-07-14 19:13:39,943 DEBUG - interface - ['] : [(48, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [z] : [(52, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [x] : [(53, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [c] : [(54, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [v] : [(55, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [b] : [(56, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [n] : [(57, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [m] : [(58, 0)]
2016-07-14 19:13:39,943 DEBUG - interface - [,] : [(59, 0), (61, 3)]
2016-07-14 19:13:39,944 DEBUG - interface - [.] : [(60, 0), (61, 2)]
2016-07-14 19:13:39,944 DEBUG - interface - [/] : [(61, 0), (94, 2), (51, 3)]
2016-07-14 19:13:39,944 DEBUG - interface - [Q] : [(24, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [W] : [(25, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [E] : [(26, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [R] : [(27, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [T] : [(28, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [Y] : [(29, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [U] : [(30, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [I] : [(31, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [O] : [(32, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [P] : [(33, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [{] : [(34, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [}] : [(35, 1)]
2016-07-14 19:13:39,944 DEBUG - interface - [A] : [(38, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [S] : [(39, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [D] : [(40, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [F] : [(41, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [G] : [(42, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [H] : [(43, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [J] : [(44, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [K] : [(45, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [L] : [(46, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [:] : [(47, 1), (15, 3)]
2016-07-14 19:13:39,945 DEBUG - interface - ["] : [(48, 1), (11, 3)]
2016-07-14 19:13:39,945 DEBUG - interface - [Z] : [(52, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [X] : [(53, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [C] : [(54, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [V] : [(55, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [B] : [(56, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [N] : [(57, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [M] : [(58, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [<] : [(94, 0), (59, 1)]
2016-07-14 19:13:39,945 DEBUG - interface - [>] : [(60, 1), (94, 1)]
2016-07-14 19:13:39,946 DEBUG - interface - [?] : [(61, 1), (16, 3)]
2016-07-14 19:13:39,946 DEBUG - iomediator - Set modifier <capslock> to False
2016-07-14 19:13:39,946 DEBUG - iomediator - Set modifier <numlock> to True
2016-07-14 19:13:39,948 DEBUG - interface - Grabbing hotkey: ['<super>'] 'k'
2016-07-14 19:13:39,948 DEBUG - interface - Grabbing hotkey: ['<shift>', '<super>'] 'k'
2016-07-14 19:13:39,948 DEBUG - interface - Grabbing hotkey: ['<super>'] 'z'
2016-07-14 19:13:39,954 INFO - interface - XRecord interface thread starting
2016-07-14 19:13:39,954 INFO - service - Service now marked as running
2016-07-14 19:13:40,015 DEBUG - phrase-menu - Sorting phrase menu by usage count
2016-07-14 19:13:40,016 DEBUG - phrase-menu - Triggering menu item by position in list
2016-07-14 19:13:40,019 INFO - root - Entering main()
2016-07-14 19:13:46,761 DEBUG - service - Received mouse click - resetting buffer
2016-07-14 19:13:47,949 DEBUG - service - Raw key: '1', modifiers: [], Key: 1
2016-07-14 19:13:47,950 DEBUG - service - Window visible title: 'New Issue · guoci/autokey-py3 - Mozilla Firefox', Window class: 'Navigator.Firefox'
2016-07-14 19:13:47,950 DEBUG - service - No phrase/script matched hotkey
2016-07-14 19:13:47,950 DEBUG - service - Input stack at end of handle_keypress: deque(['1'], maxlen=150)
2016-07-14 19:13:48,077 DEBUG - service - Raw key: '2', modifiers: [], Key: 2
2016-07-14 19:13:48,077 DEBUG - service - Window visible title: 'New Issue · guoci/autokey-py3 - Mozilla Firefox', Window class: 'Navigator.Firefox'
2016-07-14 19:13:48,077 DEBUG - service - No phrase/script matched hotkey
2016-07-14 19:13:48,077 DEBUG - service - Input stack at end of handle_keypress: deque(['1', '2'], maxlen=150)
2016-07-14 19:13:48,317 DEBUG - service - Raw key: '3', modifiers: [], Key: 3
2016-07-14 19:13:48,318 DEBUG - service - Window visible title: 'New Issue · guoci/autokey-py3 - Mozilla Firefox', Window class: 'Navigator.Firefox'
2016-07-14 19:13:48,318 DEBUG - service - No phrase/script matched hotkey
2016-07-14 19:13:48,318 DEBUG - service - Input stack at end of handle_keypress: deque(['1', '2', '3'], maxlen=150)
2016-07-14 19:13:49,093 DEBUG - service - Raw key: ' ', modifiers: [], Key:  
2016-07-14 19:13:49,093 DEBUG - service - Window visible title: 'New Issue · guoci/autokey-py3 - Mozilla Firefox', Window class: 'Navigator.Firefox'
2016-07-14 19:13:49,093 DEBUG - service - No phrase/script matched hotkey
2016-07-14 19:13:49,093 DEBUG - iomediator - Send via event interface
2016-07-14 19:13:49,094 DEBUG - service - Input stack at end of handle_keypress: deque([], maxlen=150)
2016-07-14 19:13:49,094 DEBUG - service - Ignored locking error in handle_keypress
2016-07-14 19:13:49,095 DEBUG - interface - Send special key: ['<backspace>']
2016-07-14 19:13:49,096 DEBUG - interface - Send special key: ['<backspace>']
2016-07-14 19:13:49,096 DEBUG - interface - Send special key: ['<backspace>']
2016-07-14 19:13:49,097 DEBUG - interface - Send special key: ['<backspace>']
2016-07-14 19:13:49,097 DEBUG - interface - Sending string: '1,2,3:hello!йцукенг98 '
2016-07-14 19:13:49,102 DEBUG - interface - Send special key: ['<left>']
2016-07-14 19:13:49,102 DEBUG - interface - Send special key: ['<left>']
2016-07-14 19:13:49,103 DEBUG - interface - Send special key: ['<left>']
2016-07-14 19:13:49,103 DEBUG - interface - Send special key: ['<left>']
2016-07-14 19:13:49,104 DEBUG - interface - Send special key: ['<left>']
2016-07-14 19:13:49,105 DEBUG - interface - Send special key: ['<left>']
2016-07-14 19:13:49,105 DEBUG - interface - Send special key: ['<left>']
2016-07-14 19:13:49,106 DEBUG - interface - Send special key: ['<left>']
2016-07-14 19:13:49,106 DEBUG - interface - Send special key: ['<left>']
2016-07-14 19:13:49,107 DEBUG - interface - Send special key: ['<left>']
2016-07-14 19:13:53,257 DEBUG - service - Received mouse click - resetting buffer
2016-07-14 19:13:54,024 DEBUG - service - Received mouse click - resetting buffer
2016-07-14 19:13:54,122 INFO - root - Shutting down
2016-07-14 19:13:54,122 INFO - service - Service shutting down
2016-07-14 19:13:55,120 INFO - config-manager - Persisting configuration
2016-07-14 19:13:55,120 INFO - config-manager - Backing up existing config file
2016-07-14 19:13:55,121 DEBUG - inotify - Reporting IN_MODIFY event at /home/dm/.config/autokey/autokey.json~
2016-07-14 19:13:55,121 DEBUG - inotify - Reporting IN_MODIFY event at /home/dm/.config/autokey/autokey.json~
2016-07-14 19:13:55,122 DEBUG - inotify - Reporting IN_MODIFY event at /home/dm/.config/autokey/autokey.json
2016-07-14 19:13:55,122 INFO - config-manager - Finished persisting configuration - no errors
2016-07-14 19:13:55,123 DEBUG - inotify - Reporting IN_MODIFY event at /home/dm/.config/autokey/autokey.json
2016-07-14 19:13:56,124 INFO - inotify - Shutting down file monitor
2016-07-14 19:13:56,124 DEBUG - root - All shutdown tasks complete... quitting
```

**Comment by dmgl** [comment]
Change `abbreviation from selection` script like this (below). It makes abbreviation in english from typed russian. So bad, but working solution.

```
import time
time.sleep(0.25)
contents = clipboard.get_selection()
retCode, abbr = dialog.input_dialog("New Abbreviation", "Choose an abbreviation for the new phrase")

z = [('q', 'й'),
     ('w', 'ц'),
     ('e', 'у'),
     ('r', 'к'),
     ('t', 'е'),
     ('y', 'н'),
     ('u', 'г'),
     ('i', 'ш'),
     ('o', 'щ'),
     ('p', 'з'),
     ('[', 'х'),
     (']', 'ъ'),
     ('a', 'ф'),
     ('s', 'ы'),
     ('d', 'в'),
     ('f', 'а'),
     ('g', 'п'),
     ('h', 'р'),
     ('j', 'о'),
     ('k', 'л'),
     ('l', 'д'),
     (';', 'ж'),
     ("'", 'э'),
     ('z', 'я'),
     ('x', 'ч'),
     ('c', 'с'),
     ('v', 'м'),
     ('b', 'и'),
     ('n', 'т'),
     ('m', 'ь'),
     (',', 'б'),
     ('.', 'ю'),
     ('/', '.')]
     
for i in z:
    abbr = abbr.replace(i[1],i[0])

if retCode == 0:
    if len(contents) > 20:
        title = contents[0:17] + "..."
    else:
        title = contents
    folder = engine.get_folder("My Phrases")
    engine.create_abbreviation(folder, title, abbr, contents)
```

**Comment by troxor** [comment]
The warnings and errors should be fixed in git HEAD. I confirmed the same behavior with "Paste using" = Keyboard omitting the Russian characters. I'll look into this, but for now using Shift+Insert instead is a good workaround (if you don't mind your clipboard being clobbered).

**Comment by troxor** [comment]
Looking into this a bit more and comparing results of `xev` of typing the letter 'a' on a us layout, and then switching to ru:

```
KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x1da, subw 0x0, time 271557780, (39,-30), root:(1850,966),
    state 0x10, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (61) "a"
    XmbLookupString gives 1 bytes: (61) "a"
    XFilterEvent returns: False
...
...
KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x1da, subw 0x0, time 271558786, (39,-30), root:(1850,966),
    state 0x2010, keycode 38 (keysym 0x6c6, Cyrillic_ef), same_screen YES,
    XLookupString gives 2 bytes: (d1 84) "ф"
    XmbLookupString gives 2 bytes: (d1 84) "ф"
    XFilterEvent returns: False
```
Note that the same keycode is sent (corresponding to the same physical key), but the keysym is different.

Additionally, modifying `lib/autokey/interface.py` line 236 and starting with `--verbose`:
```for char in "\\|`1234567890-=~!@#$%^&*()qwertyuiop[]asdfghjkl;'zxcvbnm,./QWERTYUIOP{}ASDFGHJKL:\"ZXCVBNM<>?!йцукенгшщзхъфывапролджэячсмитьбю.":```

Results in 
```...
2017-02-06 22:39:55,307 DEBUG - interface - [a] : [(38, 0)]
...
2017-02-06 22:39:55,311 DEBUG - interface - No mapping for [ф]
...`

**Comment by metaluer** [comment]
You could use the str instead of the key command from xtest, but that can only produce two-bytes-unicode characters, the xdotool works. I made an workaround by calling scripts instead of txt-phrases, e.g.: subprocess.call(["xdotool", "type", "⁰"]) instead of ⁰

**Comment by Guraknugen** [comment]
As a workaround for those Unicode strings, if anyone is interested, I currently do scripts instead. Since `keyboard.send_keys(myString)` doesn't work in this case, I use the clipboard, but first I save the current clipboard, since I don't want the script to change the content of the clipboard.
Here's an example that types a line of 87 m-dashes and a newline character:

`OldClipboard=clipboard.get_clipboard()`
`TextToType="—" * 87 + "\n"`
`clipboard.fill_clipboard(TextToType)`
`keyboard.send_keys("<ctrl>+v")`
`time.sleep(0.1)`
`clipboard.fill_clipboard(OldClipboard)`

The delay is necessary, although I found that, at least on my system, 0.005 seconds works in most situations. If there is no delay, the `keyboard.send_keys("<ctrl>+v")` won't finish before the old content is back in the clipboard.

**Comment by gusbemacbe** [comment]
I have still problem with inserting hyphens, using abbreviations or key. When you insert an abbreviation to insert any hyphen, the hyphens did not appear:

![hyphen bugs](https://user-images.githubusercontent.com/2257024/49434917-7c780780-f79c-11e8-95ca-5cf373d90fc7.gif)

**Comment by gusbemacbe** [comment]
The hyphen Unicodes are: u2013, u2014 and u2015.

**Comment by rphair** [comment]
I can't paste a rupee symbol as a phrase using the keyboard (Ubuntu 18.04 / autokey-gtk 0.90.4-1.1).  When setting the phrase to `₹foo` it just just pastes `foo` when I press the hotkey.  This is the character I am using:
`0x20B9     &#8377;    "₹"         Currency Symbols U+020B9`

Strange that the euro symbol is also on this Unicode block, but it pastes as a phrase from the keyboard with no problem.  Maybe not so strange that the euro is one of the few characters in this block that have a named HTML entity and/or canonical name:
`0x20AC      &euro;    "€"         EURO SIGN`

**Comment by luziferius** [comment]
@rphair That is probably due to € being in your local X11 keymap, while ₹ is not. AutoKey has the tendency to fail to add such symbols to the keymap for typing purposes. Normally, AutoKey can only type the same symbols you can type using the physical keyboard in front of you. There is a workaround in place that fiddles with the X11 keymap, but it is a bit brittle.

Use the clipboard pasting mode instead, because that circumvents the issue. But then use the newest version (0.95.4, and 0.95.5 when it is published), because it has many bug/freeze/crash fixes regarding the clipboard.

**Comment by josephj11** [comment]
@rphair Unfortunately, there's no one at Debian to maintain their AutoKey package. 0.90.4 is over six years old and unmaintained. That version had lots of issues with multibyte character sets.
We still have some of those issues, but the current version is much better and adds some new features as well.

If you have phrases and scripts you need to save then:
Make a full backup of $HOME/.config/autokey (including hidden files).
Then uninstall AutoKey.
Next, follow the instructions [here](https://github.com/autokey/autokey/wiki/Installing).

That will get you up to version 0.95.1.

You can get the current version of AutoKey [here](https://github.com/autokey/autokey/releases/tag/v0.95.4) as @luziferius advised.

In addition to many bug fixes, this version also adds Xautomation support which allows you to search the screen for an image and move the mouse cursor to it - making it possible to access all sorts of things that keyboard actions alone could not reach.

This version is based on Python3.x, so if you have any scripts which use Python syntax/features which changed from Python2.x, you will have to convert them. Most simple scripts should be unaffected by these changes.

**Comment by rphair** [comment]
The last couple of comments are really helpful; I appreciate knowing the limitations of AutoKey and how to work with it if necessary.  It is looking like xmodmap may be a better way to go for single characters.  It would be great to be able to use AutoKey as well.

Please let me ask one off-topic question since it's raised by the @luziferius comment above: does anyone know an Ubuntu 18.04 input source (keyboard) that has _both_ the rupee and euro symbols on it?  For anyone interested (the rest please forgive me):

- According to the keymap display in GNOME the keyboard layout called [English (India, with rupee)](https://itsfoss.com/type-rupee-symbol-ubuntu/) has the rupee as RightAlt-4 and NO other Alt- graphic characters.  I even bought what I believe is the corresponding "English (India)" physical keyboard with the rupee and euro symbols printed as RightAlt-4 and -5, but with this keymap the euro can neither be typed nor inserted with AutoKey in keyboard mode.

**Comment by luziferius** [comment]
Oh, I think I’ve written something misleading… AutoKey can type everything you can press without modifier keys, based on your _configured_ primary keyboard layout. Because that layout (most probably) matches the keyboard in front of you, I compared it to the physical keyboard.
It does not mean you have to buy a real physical keyboard of the desired layout. You can achieve the same by just configuring your desktop environment to use another primary layout.
You can return that keyboard, if you still can… I’m sorry about having you potentially wasted your money. I didn’t want to imply that the presence of the actual hardware is required.

All other symbols, accessible by using keyboard combinations, are typed by AutoKey by inserting a virtual key into the key map that emits the desired symbol when “pressed” unmodified and then pressing that virtual key. 
If you configured the system to use `English (India, with rupee)`, you should be able to type both symbols by placing the key combination, like `<alt_gr>+4`, into the Phrase, instead of the actual symbol.

**Comment by rphair** [comment]
please also forgive me @luziferius if I gave _you_ the wrong idea: we all know physical keyboards can be configured to work as other keyboards without having to buy another one.  I am only claiming that a physical keyboard is evidence that there must be an X11 keymap out there that corresponds to it... i.e. a GNOME Language/Regional Input Source that has both a rupee and a euro symbol on it, like you can see at the video thumbnail at [this link](https://itsfoss.com/type-rupee-symbol-ubuntu) (already included above) which looks just like the mass market keyboard in my hands now (Dell India KB216).

The problem for me is that the corresponding GNOME keyboard layout `English (India, with rupee)` doesn't match this keyboard.  Here is a [screenshot of that layout](http://cosd.com/stuff/2019-02-11-github-autokey-issue-29-keymap.jpg) in Ubuntu 18.04... note this contradicts the instructions at the "tutorial" link above, and all other "how-to"'s, because the euro cannot be generated from that keyboard when configured as such... since, as we can see, it is not in the keymap.

> If you configured the system to use `English (India, with rupee)`, you should be able to type both symbols by placing the key combination, like `<alt_gr>+4`, into the Phrase, instead of the actual symbol.

I must have missed something since that literally pastes the phrase `<alt_gr>+4` when I press the hotkey.  Although even if it did simulate that key press then it still wouldn't help, since the desired keyboard symbol is missing from that position in the keymap.  Although I've apologised for being off-topic I do believe we need to know conclusively whether AutoKey can work around inconsistencies between regional keyboards and the X11 keymaps that sometimes fail to represent them.

That is why I am begging readers here & the world to post here any GNOME keymap that has both of the euro and rupee characters on it... and if I've missed a workaround in the above then I pray someone will post more explicit instructions, in hope this will also work for the cases of missing diacritics as well (going back to the OP).  Otherwise we will have to give up on AutoKey and try to shoe-horn the missing symbol(s) into the keyboard layout with `xmodmap`.

**Comment by rphair** [comment]
p.s. I can confirm that version 0.95.1 fixes the problem on Ubuntu: we were very recently upgraded, probably via [this PPA](https://launchpad.net/~sporkwitch/+archive/ubuntu/autokey).  As the experts have said, the out-of-keymap characters will only be included in Clipboard mode, not Keyboard mode.  The deficiency in the `English (India, with rupee)`layout may again have become off topic. :)

**Comment by gusbemacbe** [comment]
And me? I am using 0.95.6. I want to hyphens.

**Comment by GrayedFox** [comment]
Hey all, just wanted to confirm this bug is still present in the Ubuntu LTS packaged gtk version (0.95.1.)

I cannot get my script to fire if the abbreviation contains a colon, i.e. `dp:s` (deploy staging). Replacing it with a period works (`dp.s` works fine). I think this is the same bug no?

Extra info: external US international keyboard plugged into a laptop that defaults to German keyboard layout, as it has a German keyboard. Not sure if this is relevant.

**Comment by Lonniebiz** [comment]
**Related:** https://stackoverflow.com/questions/11184300/

**Comment by Elliria** [comment]
A possible solution is here: #532

**Comment by josephj11** [comment]
For anyone finding this old issue, please see our wiki [here](https://github.com/autokey/autokey/wiki/Emitting-Keyboard-Events) and [here](https://github.com/autokey/autokey/wiki/Unicode-Characters) for help with non-EN-US characters.
